### ISSUE TITLE
Vertical bar appearing two times in the definition box

### ISSUE THREAD

**Issue by V2power** [BrenoAqua/Senren#15]
For some reason, in some words, the vertical bar character appear twice to separate different meanings.

![Image](https://github.com/user-attachments/assets/b960dadc-6a98-47fa-97e3-388c1cb09c04)

I noticed that in the styling of the Senren card, the vertical bar is added to separate different meanings, but for some words, seems that Yomitan already adds by default. I think this problem isn't related to the Senren card type itself, and this is only a cosmetic problem but, it is possible to remove this ::before vertical bar?

Thank you for this amazing note type!

**Comment by BrenoAqua** [comment]
Yes, it is. You can probably fix this by removing the following from the CSS:

```css
[data-sc-content="glossary"] {
  display: flex;
  flex-wrap: wrap;
  padding: 0;
  margin: 0;
}

[data-sc-content="glossary"] li:not(:last-child)::after {
  content: "|";
  color: var(--text-color-muted);
  margin: 0 var(--spacing-ms);
}
```

Maybe it’s due to a setting in Yomitan? It has never displayed separators like that for me (my Jitendex is up to date).

![Image](https://github.com/user-attachments/assets/f3263398-95b6-4d30-b91e-8082903a1ccd)
